/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelDominio.Pet;
import modelDominio.Usuario;
import view.utils.ComboBoxUsuario;
import view.utils.Imagem;

/**
 *
 * @author aluno
 */
public class TelaCadastroPet extends javax.swing.JFrame {

    private Pet pet;
    private Imagem imagem = null;
    TelaConsultaPet telaConsulta;
    /**
     * Creates new form TelaCadastroPet
     */
    public TelaCadastroPet(TelaConsultaPet telaConsulta) {
        initComponents();
        preencheComboboxUsuarios(-1);
        this.telaConsulta = telaConsulta;
    }
    
    public TelaCadastroPet(Pet pet, TelaConsultaPet telaConsulta) {
        initComponents();
        preencheComboboxUsuarios(-1);
        this.telaConsulta = telaConsulta;
        setPet(pet);
    }
    
    public void preencheComboboxUsuarios(int codigo) {
        ArrayList<Usuario> listaUsuarios = new ArrayList<Usuario>();
        listaUsuarios = Principal.ccont.usuarioLista();
        ComboBoxUsuario.preencheComboBoxUsuario(codigo, jComboBox1, listaUsuarios, false);
    }
    
    public void setPet(Pet p) {
        nomePet.setText(p.getNomePet());
        especie.setText(p.getEspecie());
        raca.setText(p.getRaca());
        if(p.getFoto() != null) {
            Imagem imagem = new Imagem(p.getFoto());
            labelImagem.setIcon(imagem.getImageIcon());
        }
        preencheComboboxUsuarios(p.getDono().getCodUsuario());
        this.pet = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnSalvar = new javax.swing.JButton();
        jBtnSair = new javax.swing.JButton();
        nomePet = new javax.swing.JTextField();
        especie = new javax.swing.JTextField();
        raca = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonCarregarImagem = new javax.swing.JButton();
        labelImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome do Pet:");

        jLabel2.setText("raça:");

        jLabel3.setText("especie:");

        jLabel4.setText("Dono:");

        jBtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/adicionar.png"))); // NOI18N
        jBtnSalvar.setText("Salvar");
        jBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarActionPerformed(evt);
            }
        });

        jBtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/voltar.png"))); // NOI18N
        jBtnSair.setText("Sair");
        jBtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSairActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonCarregarImagem.setText("Carregar Imagem");
        jButtonCarregarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarregarImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomePet, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(especie)
                                    .addComponent(raca)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButtonCarregarImagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(especie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(raca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCarregarImagem)
                .addGap(15, 15, 15)
                .addComponent(labelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarActionPerformed
        int codUsuario = ComboBoxUsuario.getSelectedIndex(jComboBox1);
        
        if(nomePet.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Peencha o nome");
            nomePet.requestFocus();
        }
        if(especie.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Peencha a especie");
            especie.requestFocus();
        }
        if(raca.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Peencha a raça");
            raca.requestFocus();
        }else {
            boolean result = false;
            if(pet != null) {
                Pet petEditar;
                if(imagem!= null) {
                    petEditar = new Pet(pet.getCodPet(), nomePet.getText(), especie.getText(), raca.getText(), new Usuario(codUsuario), imagem.getImagem());                                       
                } else {
                    petEditar = new Pet(pet.getCodPet(), nomePet.getText(), especie.getText(), raca.getText(), new Usuario(codUsuario), null);                                       
                }
                result = Principal.ccont.petEditar(petEditar);
            } else {
                Pet petInserir;
                if(imagem!= null) {
                    petInserir = new Pet(pet.getCodPet(), nomePet.getText(), especie.getText(), raca.getText(), new Usuario(codUsuario), imagem.getImagem());                                       
                } else {
                    petInserir = new Pet(pet.getCodPet(), nomePet.getText(), especie.getText(), raca.getText(), new Usuario(codUsuario), null);                                       
                }
                result = Principal.ccont.petInserir(petInserir);
            }
            
            if(result) {
                JOptionPane.showMessageDialog(this, "Pet adicionado/editado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro adicionando/editando pet!");
            }
        }
        telaConsulta.atualizaTabela();
        dispose();
    }//GEN-LAST:event_jBtnSalvarActionPerformed

    private void jBtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSairActionPerformed
        dispose();
    }//GEN-LAST:event_jBtnSairActionPerformed

    private void jButtonCarregarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarregarImagemActionPerformed
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        jFileChooser.addChoosableFileFilter(imageFilter);
        if(jFileChooser.showOpenDialog(this) == jFileChooser.APPROVE_OPTION) {
            try {
                imagem = new Imagem(jFileChooser.getSelectedFile());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(TelaCadastroPet.class.getName()).log(Level.SEVERE, null, ex);
            }
            labelImagem.setIcon(imagem.getImageIcon());
        }
    }//GEN-LAST:event_jButtonCarregarImagemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField especie;
    private javax.swing.JButton jBtnSair;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JButton jButtonCarregarImagem;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JTextField nomePet;
    private javax.swing.JTextField raca;
    // End of variables declaration//GEN-END:variables
}
